# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
  
language: R
sudo: required
dist: trusty
cache: packages

install:
    # Install GenomicsDB
    - source .travis/install_genomicsdb.sh

    # Install R package dependencies 
    - R -e 'install.packages("devtools", dependencies=TRUE)'
    - R -e 'install.packages(c("testthat", "roxygen2"))'

script:
    # Build and Test R package
    - R -e 'library(Rcpp); compileAttributes(".")'
    - R CMD build .
    - R CMD INSTALL --preclean --configure-args="--with-genomicsdb=${TRAVIS_BUILD_DIR}" genomicsdb_0.0.1.tar.gz
    - R -f tests/test.R

