# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
  
language: R
sudo: required
dist: trusty
cache: packages

install:
    # Install GenomicsDB
    - source .travis/install_genomicsdb.sh

    # Install R package dependencies 
    - R -e 'install.packages("devtools", dependencies=TRUE)'
    - R -e 'install.packages(c("testthat", "roxygen2"))'

script:
    # Build and Test R package
    - configure --with-genomicsdb=${HOME}
    - R CMD build .
    - R CMD INSTALL --preclean --configure-args="--with-genomicsdb=${HOME}" genomicsdb_0.0.2.tar.gz
    - R CMD check --no-manual genomicsdb_0.0.2.tar.gz
    - R -e 'library(devtools); test()'

