# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

os: linux
dist: bionic
sudo: true
r:
    - oldrel
    - release
    - devel

cache:
    - packages
    - ccache

repos:
  CRAN: http://cran.rstudio.com

apt_packages:
    - libxml2-dev

install:
    # Install R package dependencies
    - R -e 'install.packages("devtools", dependencies=TRUE)'
    - R -e 'install.packages(c("testthat", "roxygen2"))'

    # Install GenomicsDB
    - source .travis/install_genomicsdb.sh

script:
    # Build and Test R package
    - R CMD build .
    - R CMD INSTALL --configure-args="--with-genomicsdb=${GENOMICSDB_HOME}"  genomicsdb_0.0.3.tar.gz
    - R CMD check --no-manual --install-args="--configure-args='--with-genomicsdb=${GENOMICSDB_HOME}'" genomicsdb_0.0.3.tar.gz
    - R -e 'library(devtools); devtools::test()'
