# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

version <- function() {
    .Call(`_genomicsdb_version`)
}

connect <- function(workspace, vid_mapping_file, callset_mapping_file, attributes, segment_size = 10*1024*1024L) {
    .Call(`_genomicsdb_connect`, workspace, vid_mapping_file, callset_mapping_file, attributes, segment_size)
}

connect_with_query_json <- function(query_configuration_json_file, loader_configuration_json_file, concurrency_rank = 0L) {
    .Call(`_genomicsdb_connect_with_query_json`, query_configuration_json_file, loader_configuration_json_file, concurrency_rank)
}

disconnect <- function(genomicsdb) {
    invisible(.Call(`_genomicsdb_disconnect`, genomicsdb))
}

query_variants <- function(genomicsdb, array, column_ranges, row_ranges) {
    .Call(`_genomicsdb_query_variants`, genomicsdb, array, column_ranges, row_ranges)
}

query_variant_calls <- function(genomicsdb, array, column_ranges, row_ranges) {
    .Call(`_genomicsdb_query_variant_calls`, genomicsdb, array, column_ranges, row_ranges)
}

query_variant_calls_json <- function(genomicsdb) {
    .Call(`_genomicsdb_query_variant_calls_json`, genomicsdb)
}

query_variant_calls_by_interval <- function(genomicsdb, array, column_ranges, row_ranges) {
    .Call(`_genomicsdb_query_variant_calls_by_interval`, genomicsdb, array, column_ranges, row_ranges)
}

generate_vcf <- function(genomicsdb, array, column_ranges, row_ranges, reference_genome, vcf_header, output, output_format, overwrite) {
    invisible(.Call(`_genomicsdb_generate_vcf`, genomicsdb, array, column_ranges, row_ranges, reference_genome, vcf_header, output, output_format, overwrite))
}

generate_vcf_json <- function(genomicsdb, output, output_format, overwrite) {
    invisible(.Call(`_genomicsdb_generate_vcf_json`, genomicsdb, output, output_format, overwrite))
}

rcpp_hello_world <- function() {
    .Call(`_genomicsdb_rcpp_hello_world`)
}

rcpp_vector_access1 <- function() {
    invisible(.Call(`_genomicsdb_rcpp_vector_access1`))
}

