# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

version <- function() {
    .Call(`_genomicsdb_version`)
}

setup <- function(workspace, vid_mapping_file, callset_mapping_file, reference_genome, attributes) {
    .Call(`_genomicsdb_setup`, workspace, vid_mapping_file, callset_mapping_file, reference_genome, attributes)
}

setup_from_json <- function(query_configuration_json_file, loader_configuration_json_file) {
    .Call(`_genomicsdb_setup_from_json`, query_configuration_json_file, loader_configuration_json_file)
}

query_variants <- function(genomicsdb, array, column_ranges, row_ranges) {
    .Call(`_genomicsdb_query_variants`, genomicsdb, array, column_ranges, row_ranges)
}

rcpp_hello_world <- function() {
    .Call(`_genomicsdb_rcpp_hello_world`)
}

rcpp_vector_access1 <- function() {
    invisible(.Call(`_genomicsdb_rcpp_vector_access1`))
}

