#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-build

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.rst'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.rst'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04,macos-10.15]
        r-version: ['3.6.3', '4.1.1']

    runs-on: ${{matrix.os}}
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          install.packages("devtools", dependencies=TRUE)
          install.packages(c("testthat", "roxygen2"))
        shell: Rscript {0}
        
      - name: Build and Test
        run: |
          source $GITHUB_WORKSPACE/.github/scripts/install_genomicsdb.sh
          $GITHUB_WORKSPACE/build.sh
        shell: bash

